[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1" }
serde_json = "1"
extism-pdk = { version = "0.1.0"}
